throttle_scans: 1 
base_frame: base_link 
map_frame: map 
odom_frame: odom 
map_update_interval: 10 
maxUrange: 5.5 
maxRange: 5.5 
sigma: 0.05 
kernelSize: 1 
lstep: 0.05 
astep: 0.05 
iterations: 5 
lsigma: 0.075 
ogain: 3.0 
lskip: 0 
minimumScore: 50.0 
srr: 0.1 
srt: 0.2 
str: 0.1 
stt: 0.2 
linearUpdate: 0.2
angularUpdate: 0.25
temporalUpdate: 5.0
resampleThreshold: 0.5 
particles: 30 
xmin: -10 
xmax: 10 
ymin: -10 
ymax: 10 
delta: 0.025 
llsamplerange: 0.01 
llsamplestep: 0.01 
asamplerange: 0.005 
lasamplestep: 0.005 
transform_publish_period: 0.1 
occ_thresh: 0.25